### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by cringasu-ionut** [luyadev/luya-module-account#1]
is this module finished? if yes, how can i install it?

**Comment by nadar** [comment]
Hi @cringasuionut - no sadly not, we are working an a full overhaul. You can of course install the RC4 version by adding `luyadev/luya-module-account:1.0.0-RC4`.

**Comment by JohnnyMcWeed** [comment]
Hey @nadar - are there any news on this? Is there a planned date for release?

**Comment by nadar** [comment]
I started in this branch with some new ideas => https://github.com/luyadev/luya-module-account/tree/concept

But currently i have no time to finish, maybe someone like to help me?

**Comment by JohnnyMcWeed** [comment]
In a month or so I'll probably have some moments I can help.

I just checked through your latest commit... So what kind of changements did you want to come up with? What ideas do you have in mind concerning the account module?

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
